version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.final
    container_name: approval-workflow-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - approval-network
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=approval_workflow
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword

  webserver:
    image: nginx:alpine
    container_name: approval-workflow-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - approval-network
    depends_on:
      - app

  database:
    image: mariadb:10.9
    container_name: approval-workflow-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: approval_workflow
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - approval-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: approval-workflow-pma
    restart: unless-stopped
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    networks:
      - approval-network
    depends_on:
      - database

  selenium-hub:
    image: selenium/hub:4.15.0-20231110
    container_name: approval-workflow-selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    networks:
      - approval-network

  chrome:
    image: selenium/node-chrome:4.15.0-20231110
    container_name: approval-workflow-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - approval-network

volumes:
  db_data:
    driver: local

networks:
  approval-network:
    driver: bridge